resources: Floyd-Warshall patch
gem5/gem5-resources pull request #18
Opened 2023-12-18 22:29 UTC by jebraun3

Change-Id: Iaf10a340d1d3eda73441b112ef285fd6151c1df5

2023-12-18 22:42 UTC, mattsinc commented
@BobbyRBruce I believe this fixes most/all of the things you raised in #15

2023-12-18 22:42 UTC, mattsinc approved these changes, later dismissed

2024-02-09 03:10 UTC, mattsinc requested changes
one minor thing!

2024-02-09 03:10 UTC, mattsinc commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
> +                fprintf(stderr, "SWITCHES\n    -f [file name]\n            input file name\n");
I'm not sure if it's the way it's showing up on Github, but I think it would be cleaner if you had each option start on a new line in the cpp file.

2024-02-16 17:06 UTC, mattsinc requested changes
Almost there!

2024-02-16 17:06 UTC, mattsinc commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
> +    }
175-177 are using tabs instead of spaces

2024-02-24 23:28 UTC, mattsinc approved these changes
Nice job!

2024-02-24 23:28 UTC, mattsinc commented
@BobbyRBruce let us know if you want us to hold off on merging this or if it's ok to merge

2024-02-26 16:26 UTC, powerjg commented
Is this just style changes or does this have functional change too? Do we need to build a new binary for gem5-resources?

cc: @Harshil2107

2024-02-26 20:22 UTC, mattsinc commented
> Is this just style changes or does this have functional change too? Do we need to build a new binary for gem5-resources?
> 
> cc: @Harshil2107

I believe this is completely stylistic things @BobbyRBruce had asked for after https://github.com/gem5/gem5-resources/pull/15

2024-02-26 20:23 UTC, mattsinc commented
> > Is this just style changes or does this have functional change too? Do we need to build a new binary for gem5-resources?
> > cc: @Harshil2107
> 
> I believe this is completely stylistic things @BobbyRBruce had asked for after #15

So technically yes a new binary would be needed to incorporate this, but since it's really just style or prints being affected I don't think it's urgent or important to do (@BobbyRBruce may disagree).

2024-02-26 20:23 UTC, merged