resources: Add a tutorial on adding workloads
gem5/gem5-resources pull request #2
Opened 2023-07-27 19:59 UTC by kunpai

This document details how to add a Resource, wrap it in a Workload, and test the Workload with the new gem5 Resources infrastructure introduced in v23.0.

2023-07-27 20:22 UTC, powerjg commented on ADDING-WORKLOADS.md
> +To test the Workload, we first have to add the local JSON file as a data source for gem5. This can be done by navigating to `src/python/gem5_default_config.py` and adding a JSON object to `"sources"`
I really don't like this suggestion. We should not require people to modify something in source and recompile gem5 just to test a local workload.

Do we not have a way to use an environment variable to point to a json file? If not, we should add that!

2023-07-27 20:43 UTC, kunpai commented on ADDING-WORKLOADS.md
> +To test the Workload, we first have to add the local JSON file as a data source for gem5. This can be done by navigating to `src/python/gem5_default_config.py` and adding a JSON object to `"sources"`
According to this function we wrote: [https://github.com/gem5/gem5/blob/af72b9ba580546ac12ce05bfaac3fd53fa8699f4/src/python/gem5/resources/client.py#L53](https://github.com/gem5/gem5/blob/af72b9ba580546ac12ce05bfaac3fd53fa8699f4/src/python/gem5/resources/client.py#L53), we can either place a gem5 resources config file in the cwd or pass its path in through GEM5_CONFIG while building. So, I should indicate those two options?

2023-07-27 20:53 UTC, powerjg commented on ADDING-WORKLOADS.md
> +To test the Workload, we first have to add the local JSON file as a data source for gem5. This can be done by navigating to `src/python/gem5_default_config.py` and adding a JSON object to `"sources"`
Yes! Thanks :)

2023-08-03 15:14 UTC, powerjg submitted a review, later dismissed

2023-08-16 05:00 UTC, BobbyRBruce requested changes

2023-08-16 05:00 UTC, BobbyRBruce commented on ADDING-WORKLOADS.md
> +```
How is the user supposed to set the path to the the binary resource in this case?

2023-08-16 05:00 UTC, BobbyRBruce commented on ADDING-WORKLOADS.md
> +## Introduction
I would explain what a workload is. Particularly that it declaring a function call to a board.

`board.set_workload('x')` -> this. The Workload with ID 'x' will be parsed and it will be used to construction the function call it defines.

2023-08-16 05:00 UTC, BobbyRBruce commented on ADDING-WORKLOADS.md
> +    "function": "set_se_binary_workload",
I'd link to the `set_se_binary_workload` function here and explain the `resources` field here specifies the setting of the binary. You should also mention that the `additional_parameters` field. Why not have this binary accept some arguments?

2023-08-16 17:29 UTC, kunpai commented on ADDING-WORKLOADS.md
> +```
I can look into this, but my purpose of not mentioning it was also on the base assumption that the Resource should exist on gem5 Resources before one makes a Workload of it. Should we allow both to be done simultaneously?

With the REU cohort, they are making Workloads out of Resources that already exist or are making the Resource first before they make a Workload, which is why the tutorial follows its current flow.

2023-08-16 17:30 UTC, kunpai commented on ADDING-WORKLOADS.md
> +    "function": "set_se_binary_workload",
I like this suggestion!

2023-08-16 17:30 UTC, kunpai commented on ADDING-WORKLOADS.md
> +## Introduction
Sounds good! I'll work on it.

2023-08-16 17:33 UTC, BobbyRBruce commented on ADDING-WORKLOADS.md
> +```
I don't think this makes much sense. Perhaps I'm missing something. If you define the resource inside the local JSON file then it'll use that resource. In this case `binary-resource`. That resource is not in the database. How is gem5 supposed to know where this binary is?

2023-08-16 21:17 UTC, powerjg requested changes
Before merging, can you clean up the git history (i.e., rebase and/or squash) into a human-understandable history?

2023-08-17 23:00 UTC, closed without merging

2023-08-22 00:46 UTC, BobbyRBruce commented
Did you mean to close this?

2023-08-22 01:24 UTC, kunpai commented
Yes, I need to edit the tutorial. I will reopen it once Workloads are deprecated and my change on supporting paths is merged