Added mmap support for both color benchmark variants
gem5/gem5-resources pull request #28
Opened 2024-03-24 00:48 UTC by jebraun3

Change-Id: Iacc15529befcf5f1541b0209dc32eebf689f2725

Adds mmap support to both color benchmark variants

2024-03-24 23:34 UTC, mattsinc requested changes
I thought you were going to push all of the other Pannotia benchmarks publicly at once to avoid needing to review them one by one?  In any event, since it's here, let's just review and commit it!

One thing: I believe the only difference between maxmin's and max's changes are the max() call?  If so, maybe we should make a header file for all of this to avoid almost the same code twice?

2024-03-24 23:34 UTC, mattsinc commented on src/gpu/pannotia/color/coloring_max.cpp
> +
will need to remove

2025-02-27 22:10 UTC, erin-le commented
@jebraun3: Hello, this PR is being closed for inactivity. If you would like to continue working on it, please feel free to reopen it. Thank you!

2025-02-28 16:35 UTC, mattsinc commented
@erin-le: @jebraun3 is away on co-op, I will add this to my list to merge.  Won't be today though.

2025-03-22 21:14 UTC, mattsinc approved these changes
@abmerop , @erin-le I have made the changes I asked @jebraun3 to make previously.  I've approved to kickstart any runs that may happen, but will wait for someone to review before merging.

2025-03-26 18:55 UTC, powerjg commented
lgtm. @erin-le do we have a binary on gem5-resources for color and color-maxmin? If so, we need to upload a new version. If not, then we can just merge this now.

2025-03-26 19:14 UTC, erin-le commented
@powerjg: Searches on the gem5 resources website for "color" and "pannotia" don't yield any results, so the binaries probably aren't on the website. @Harshil2107 might have a better idea though.

2025-03-26 19:17 UTC, Harshil2107 commented
There are binaries for "color" and "pannotia" on the cloud bucket, I will remake them and push them to the bucket.

Should I make the resource JSON? As far as I know we dont use obtain resource on the gpu binaries.

2025-03-26 19:48 UTC, powerjg commented
Just replace the binary on the cloud bucket.

2025-03-26 19:49 UTC, powerjg approved these changes

2025-03-26 22:01 UTC, mattsinc commented
> Just replace the binary on the cloud bucket.

@Harshil2107 let me know when that is done -- I won't merge until you confirm.

2025-04-01 15:57 UTC, mattsinc commented
> > Just replace the binary on the cloud bucket.
> 
> @Harshil2107 let me know when that is done -- I won't merge until you confirm.

@Harshil2107 just checking on this again

2025-04-04 18:20 UTC, Harshil2107 commented
Sorry for the late reply, I will be updating the resources today.

2025-04-05 18:59 UTC, merged

2025-04-05 19:32 UTC, Harshil2107 commented
@mattsinc: I wanted to clarify the should I be replacing the older binaries or do we keep the older binaries?

Currently on the cloud bucket the binaries made from this PR are at:

https://storage.googleapis.com/dist.gem5.org/dist/v24-0/test-progs/pannotia/color_max.gem5_20250404
https://storage.googleapis.com/dist.gem5.org/dist/v24-0/test-progs/pannotia/color_maxmin.gem5_20250404

2025-04-05 19:33 UTC, mattsinc commented
> @mattsinc: I wanted to clarify the should I be replacing the older binaries or do we keep the older binaries?
> 
> Currently on the cloud bucket the binaries made from this PR are at:
> 
> https://storage.googleapis.com/dist.gem5.org/dist/v24-0/test-progs/pannotia/color_max.gem5_20250404 https://storage.googleapis.com/dist.gem5.org/dist/v24-0/test-progs/pannotia/color_maxmin.gem5_20250404

My understanding from my offline conversation with @powerjg is that we are replacing the old binaries, but Jason can confirm