add riscv ubuntu 22.04 image
gem5/gem5-resources pull request #30
Opened 2024-04-17 21:24 UTC by Harshil2107

This diskimage follows similar structure as the new x86 image. This image does not have readme.md or building.md as this will be merged with the x86 and arm images to a single source.

2024-05-09 17:57 UTC, powerjg reviewed
Please put newlines at the end of files.

Check to see if any of my other comments on the Arm version need any updates here.

2024-05-09 17:57 UTC, powerjg commented on src/riscv-ubuntu-22.04/riscv-ubuntu.pkr.hcl
> +                  "<wait90>",
Where does this 90 come from? Is there any way to know when the it's ready?

2024-05-09 17:57 UTC, powerjg commented on src/riscv-ubuntu-22.04/riscv-ubuntu.pkr.hcl
> +  iso_urls         = ["/home/harshilp/forks/gem5-resources-repo/fresh-riscv-img.img"]
This can't be committed with you local file paths

2024-05-09 17:57 UTC, powerjg commented on src/riscv-ubuntu-22.04/riscv-ubuntu.pkr.hcl
> +  disk_size        = "5000"
Do we have to use a disk this big?

2024-05-09 22:12 UTC, Harshil2107 commented on src/riscv-ubuntu-22.04/riscv-ubuntu.pkr.hcl
> +                  "<wait90>",
It took around 60 seconds to boot so I added a 30 second buffer. The only way to know when its booted is to have the display.

2024-05-09 22:29 UTC, Harshil2107 commented on src/riscv-ubuntu-22.04/riscv-ubuntu.pkr.hcl
> +  disk_size        = "5000"
About 4.1GB is used so I have 900MB for extra things that users might want to install.

2024-05-10 00:04 UTC, powerjg commented on src/riscv-ubuntu-22.04/riscv-ubuntu.pkr.hcl
> +                  "<wait90>",
You should document this in the README

2024-05-14 14:45 UTC, powerjg commented on src/riscv-ubuntu-22.04/.gitignore
> +disk-image/
Missing newline. Please look through your diffs and do a self code review when pushing commits.

2024-06-11 16:45 UTC, Harshil2107 commented on src/riscv-ubuntu-22.04/riscv-ubuntu.pkr.hcl
> +  iso_urls         = ["/home/harshilp/forks/gem5-resources-repo/fresh-riscv-img.img"]
I updated it to be a relative path from the current directory and the `build.sh` file downloads the image.

2024-06-11 16:59 UTC, powerjg requested changes
This looks OK. However, it's missing a README.md and a BUILDING.md. Also, IIRC, there are changes to files that were requested in other PRs (e.g., comments on `popd` lines) that have not been reflected here. (The newlines are fine, btw)

2024-06-11 16:59 UTC, powerjg commented on src/riscv-ubuntu-22.04/build.sh
> +    rm packer_${PACKER_VERSION}_linux_amd64.zip;
This should not be addressed in the current changeset, but it's now becoming a very high priority to address. We can't have the host CPU (i.e., which packer to download) tied to the guest that we are working on. Please open an issue about this. I can explain in more detail, if needed.

2024-06-11 16:59 UTC, powerjg commented on src/riscv-ubuntu-22.04/scripts/post-installation.sh
> +# netplan apply
Why is this commented out?

2024-06-11 16:59 UTC, powerjg commented on src/riscv-ubuntu-22.04/riscv-ubuntu.pkr.hcl
> +                  "<wait120>",
This should be documented in the BUILDING.md

2024-06-12 17:58 UTC, Harshil2107 commented on src/riscv-ubuntu-22.04/scripts/post-installation.sh
> +# netplan apply
for 24.04 it causes the build process to hang as when this line is reached and the change to the yamls is applied instantly and it cuts off the ssh connection causing the build to fail. By disabling the networkd wait online service , we no longer need to netplan apply immidiately, so I commented the line. I will remove the line as it is not necessary.

2024-06-12 19:20 UTC, Harshil2107 commented on src/riscv-ubuntu-22.04/riscv-ubuntu.pkr.hcl
> +                  "<wait120>",
I have added the BUILDING.md file, this follows the same structure as the x86 BUILDING.md but with modifications pertaining to the riscv image.

2024-06-12 19:21 UTC, Harshil2107 commented on src/riscv-ubuntu-22.04/build.sh
> +    rm packer_${PACKER_VERSION}_linux_amd64.zip;
I will make an issue. Just to clarify, the issue is that we are replying on the host system to figure out which packer to download but there should be some automated way? or some sort of error message when wrong packer is downloaded?

2024-06-12 20:43 UTC, powerjg commented on src/riscv-ubuntu-22.04/build.sh
> +    rm packer_${PACKER_VERSION}_linux_amd64.zip;
Either. You could certainly do the former.

In fact, we could just do `apt install packer` and not have this download thing going on...

2024-06-12 20:44 UTC, powerjg submitted a review, later dismissed
Thanks for the updates!

2024-06-13 23:29 UTC, powerjg commented on src/riscv-ubuntu-22.04/scripts/post-installation.sh
> +cat /etc/fstab
Just for the public record, I would feel more comfortable if we didn't make these changes to `fstab`. I'm particularly concerned about the change to remount in `rw` mode even if there are errors.

2024-06-17 21:03 UTC, Harshil2107 commented on src/riscv-ubuntu-22.04/build.sh
> +    rm packer_${PACKER_VERSION}_linux_amd64.zip;
https://github.com/gem5/gem5/issues/1252

2024-06-24 16:45 UTC, powerjg approved these changes

2024-06-25 17:43 UTC, merged