resources: Add kernel extract to packer
gem5/gem5-resources pull request #37
Opened 2024-05-29 18:30 UTC by Harshil2107

- Now packer also extracts the kernel that is used in the diskimage to the output directory.

2024-05-29 21:58 UTC, powerjg requested changes

2024-05-29 21:58 UTC, powerjg commented on src/x86-ubuntu/x86-ubuntu-24-04.pkr.hcl
> +  destination = "./disk-image-ubuntu-24-04/vmlinux-x86-6.8.0-31-generic"
This is going to break when Ubuntu updates the kernel (e.g., to 6.8.0-32). Maybe you should move `vmlinux-x86-$(uname -r)` to `vmlinux-x86-ubuntu` or something like that. There's probably a better way to do it..

2024-05-29 22:49 UTC, Harshil2107 commented on src/x86-ubuntu/x86-ubuntu-24-04.pkr.hcl
> +  destination = "./disk-image-ubuntu-24-04/vmlinux-x86-6.8.0-31-generic"
SHould I change it in both places, or do we want the output kernel to specify the version?

2024-05-30 01:27 UTC, powerjg commented on src/x86-ubuntu/x86-ubuntu-24-04.pkr.hcl
> +  destination = "./disk-image-ubuntu-24-04/vmlinux-x86-6.8.0-31-generic"
Yes, it needs to be done both places. However, we need a way to differentiate the kernels once we copy them out. I don't know the best way to do this.

2024-05-30 06:34 UTC, Harshil2107 commented on src/x86-ubuntu/x86-ubuntu-24-04.pkr.hcl
> +  destination = "./disk-image-ubuntu-24-04/vmlinux-x86-6.8.0-31-generic"
One thing could be that we print the kernel name in the post install, and that would show as an output. I will look into if we can have variables or programitcally name the files.

2024-05-30 16:20 UTC, powerjg approved these changes

2024-05-30 16:22 UTC, powerjg requested changes
Oops. I changed my mind. Please update the `BUILDING.md` file to explain that the kernel is extracted and that you can use that kernel as a resource.

Think about how you would need to explain this to the next person who will be maintaining gem5 resources so they can update the disk and kernel. Or, more likely, think about what information you will need in two years to do this when 26.04 is released.

2024-05-31 19:51 UTC, powerjg requested changes

2024-05-31 19:51 UTC, powerjg commented on src/x86-ubuntu/BUILDING.md
> +The kernel is extracted using packer's file provisioner with `disrection=download` which would copy a file from the image to the host machine. The path specifying in the provisioner copies the file `
```suggestion
The kernel is extracted using packer's file provisioner with `direction=download` which would copy a file from the image to the host machine. The path specifying in the provisioner copies the file `/home/gem5/vmlinux-x86-ubuntu` to the output directory `disk-image`.
```

2024-05-31 19:51 UTC, powerjg commented on src/x86-ubuntu/BUILDING.md
> +A kernel is also extracted from the diskimage during the post-installation process.
```suggestion
A kernel is also extracted from the disk image during the post-installation process.
```

2024-05-31 19:51 UTC, powerjg commented on src/x86-ubuntu/scripts/post-installation.sh
> +systemctl mask systemd-networkd-wait-online.service
The documentation is now wrong about how to re-enable networking. That needs to be updated.

2024-05-31 19:51 UTC, powerjg commented on src/x86-ubuntu/x86-ubuntu-24-04.pkr.hcl
> +  destination = "./disk-image-ubuntu-24-04/vmlinux-x86-ubuntu"
Is this the only file that will be in the `disk-image-ubuntu-24-04` directory? Will the disk image be there? If so, how?

2024-05-31 20:42 UTC, Harshil2107 commented on src/x86-ubuntu/x86-ubuntu-24-04.pkr.hcl
> +  destination = "./disk-image-ubuntu-24-04/vmlinux-x86-ubuntu"
The disk image will be there as well, the output directory is different for the 24.04 image (https://github.com/gem5/gem5-resources/blob/6089e98242538e214802eb75cb908d9f400b783b/src/x86-ubuntu/x86-ubuntu-24-04.pkr.hcl#L41).

2024-06-04 20:39 UTC, powerjg approved these changes

2024-06-12 16:52 UTC, merged