resources: Merge packer files for x85 img
gem5/gem5-resources pull request #38
Opened 2024-06-03 05:03 UTC by Harshil2107

- This change merges the packer files and adds an command line argument which can be used to specify a version of ubuntu to build.

- Update build.sh to use the merged packer file

2024-06-03 21:21 UTC, powerjg requested changes
A few high-level things that aren't included in the review below.
1. `BUILDING.md` and `README.md` are x86-specific. These need to be updated.
2. What is `flash0.img`? Do we have to have it in git? It's Arm-specific (I assume), so maybe it should be in `files/arm`
3. There could be confusion between Arm host and Arm guest. This needs to be both documented well and we need to make sure that we aren't doing anything wrong.

2024-06-03 21:21 UTC, powerjg commented on src/ubuntu-generic-diskimages/scripts/post-installation.sh
>  popd
It would be good to let people know what we're popping

```suggestion
popd   # util/m5
popd   # gem5
```

2024-06-03 21:21 UTC, powerjg commented on src/ubuntu-generic-diskimages/build.sh
> +#!/bin/bash
This file should be named `build-x86.sh`

2024-06-03 21:21 UTC, powerjg commented on src/ubuntu-generic-diskimages/build-arm.sh
>  fi
The code above this is a problem. It's specific for arm *hosts*. 

So, we need to make sure that we differentiate between Arm hosts and Arm guest.

2024-07-23 17:04 UTC, powerjg reviewed
I've made some comments below, but my comments are not complete. You need to improve the consistency throughout. Don't treat arm and x86 differently. Don't treat 22.04 and 24.04 differently. E.g., if for one you call it `x86-22.04` then you should also use `arm-24.04`. *Be consistent*

2024-07-23 17:04 UTC, powerjg commented on src/ubuntu-generic-diskimages/BUILDING.md
> +dd if=/usr/share/qemu-efi-aarch64/QEMU_EFI.fd of=flash0.img conv=notrunc
Why can't you just use `/usr/share/qemu-efi-aarch64/QEMU_EFI.fd`? Why do you have to copy that file in such a strange way?

2024-07-23 17:04 UTC, powerjg commented on src/ubuntu-generic-diskimages/BUILDING.md
> +- `http-24.04`: cloud-init Ubuntu autoinstall files for ubuntu 24.04.
What about x86 24.04? There's no files for that.

2024-07-23 17:04 UTC, powerjg commented on src/ubuntu-generic-diskimages/build-arm.sh
Needs copyright, but it could be the simple SPDX block, not the full thing.

2024-07-23 17:04 UTC, powerjg commented on src/ubuntu-generic-diskimages/README.md
This definitely needs to be updated. It says "x86" and "22.04" in many places.

2024-07-23 17:04 UTC, powerjg commented on src/ubuntu-generic-diskimages/x86-ubuntu-24-04.pkr.hcl
Why is this not in `packer-scripts`?

2024-07-23 17:04 UTC, powerjg commented on src/ubuntu-generic-diskimages/packer-scripts/x86-ubuntu.pkr.hcl
> +  default = "22.04"
Change the default to 24.04

2024-07-23 17:04 UTC, powerjg commented on src/ubuntu-generic-diskimages/packer-scripts/x86-ubuntu.pkr.hcl
> +      output_dir    = "disk-image"
Change this to `disk-image-22.04`

2024-07-23 17:04 UTC, powerjg commented on src/ubuntu-generic-diskimages/packer-scripts/arm-ubuntu.pkr.hcl
> +      http_directory = "http/arm"
Change this to `http-22-04/arm

2024-07-23 17:19 UTC, Harshil2107 commented on src/ubuntu-generic-diskimages/BUILDING.md
> +dd if=/usr/share/qemu-efi-aarch64/QEMU_EFI.fd of=flash0.img conv=notrunc
We do this because we need it to be 64MB with 0s if the file is smaller.

2024-07-23 17:19 UTC, Harshil2107 commented on src/ubuntu-generic-diskimages/BUILDING.md
> +- `http-24.04`: cloud-init Ubuntu autoinstall files for ubuntu 24.04.
We dont have separate user-data for x86 22.04 and 24.04

2024-08-22 00:03 UTC, powerjg commented on src/ubuntu-generic-diskimages/BUILDING.md
>  ## Extending the Disk Image
I think you should remove this line. You are not describing *how* to extend the disk image. You are describing the changes we have made to the disk image.

2024-08-22 00:03 UTC, powerjg commented on src/ubuntu-generic-diskimages/BUILDING.md
> +- **Replace `gem5_init.sh`**: This script is what executes as the Linux init process (pid=0) immediately after Linux boot. If you have a custom initialization script, replace the default `gem5_init.s
```suggestion
- **`gem5_init.sh` replaces /sbin/init**: This script is what executes as the Linux init process (pid=0) immediately after Linux boot. This script....
```

2024-08-22 00:03 UTC, powerjg commented on src/ubuntu-generic-diskimages/BUILDING.md
> +### Adding more libraries
```suggestion
## Extending the disk image with custom files and scripts
```

2024-08-22 00:03 UTC, powerjg commented on src/ubuntu-generic-diskimages/BUILDING.md
> +- You can add more libraries to the disk image by updating the `post-installation.sh` script.
```suggestion
- You can add more packages to the disk image by updating the `post-installation.sh` script.
```

2024-08-22 00:03 UTC, powerjg commented on src/ubuntu-generic-diskimages/BUILDING.md
> +
```suggestion
> **NOTE:** You can extend this disk image by modifying the `post-installation.sh` script, but it requires building the image from scratch.
> To take a pre-built image and add new files or packages, see examples in ....
```

2024-08-22 00:03 UTC, powerjg commented on src/ubuntu-generic-diskimages/README.md
> +If you want to enable networking, you need to modify the disk image and move the file `/etc/netplan/00-installer-config.yaml.bak` or `/etc/netplan/50-cloud-init.yaml.bak` to `/etc/netplan/00-installe
Add something like "See ... for an example of how to do this"

2024-08-22 00:03 UTC, powerjg commented on src/ubuntu-generic-diskimages/README.md
> +./build/X86/gem5.opt configs/example/gem5_library/x86-ubuntu-run-with-kvm.py
```suggestion
./build/ALL/gem5.opt configs/example/gem5_library/x86-ubuntu-run-with-kvm.py
```

Let's stop using the ISA-specific builds.

2024-08-31 00:58 UTC, erin-le commented on src/ubuntu-generic-diskimages/BUILDING.md
> +- `http`: cloud-init Ubuntu autoinstall files for different versions of ubuntu for arm and x86.
```suggestion
- `http`: cloud-init Ubuntu autoinstall files for different versions of Ubuntu for Arm and x86.
```

2024-08-31 00:58 UTC, erin-le commented on src/ubuntu-generic-diskimages/BUILDING.md
> +- Networking is disabled by moving the `/etc/netplan/00-installer-config.yaml` or `/etc/netplan/50-cloud-init.yaml` file to `/etc/netplan/00-installer-config.yaml.bak` or `/etc/netplan/50-cloud-init.
Clarify which .yaml corresponds with which category of disk images.

2024-08-31 00:58 UTC, erin-le commented on src/ubuntu-generic-diskimages/README.md
> +If you want to enable networking, you need to modify the disk image and move the file `/etc/netplan/00-installer-config.yaml.bak` or `/etc/netplan/50-cloud-init.yaml.bak` to `/etc/netplan/00-installe
Clarify which disk images these belong to

2024-08-31 00:58 UTC, erin-le commented on src/ubuntu-generic-diskimages/BUILDING.md
>  The extracted kernel does not have a version its name, but the kernel version is printed as before the extraction in `post-installation.sh` script. This extracted kernel can be used as a resource for
```suggestion
The extracted kernel does not have a version in its name, but the kernel version is printed before the extraction in `post-installation.sh` script. This extracted kernel can be used as a resource for gem5 simulations and is not limited to just be used with this disk image.
```

2024-08-31 00:58 UTC, erin-le commented on src/ubuntu-generic-diskimages/BUILDING.md
> -  - If you want to enable networking, you need to modify the disk image and move the file `/etc/netplan/00-installer-config.yaml.bak` to `/etc/netplan/00-installer-config.yaml`.
Clarify which disk images these files correspond to

2024-08-31 01:01 UTC, erin-le commented on src/ubuntu-generic-diskimages/BUILDING.md
> +If you need to increase the size of the image when adding more libraries and files to the image update the size of partition in the respective `user-data` file. Also, update the `disk_size` parameter
```suggestion
If you need to increase the size of the image when adding more libraries and files to the image update the size of the partition in the respective `http/*/user-data` file. Also, update the `disk_size` parameter in `post-installation.sh` to be at least one mega byte more than
```

2024-09-03 20:34 UTC, erin-le requested changes

2024-09-03 20:34 UTC, erin-le commented on src/ubuntu-generic-diskimages/BUILDING.md
> +To take a pre-built image and add new files or packages, see the post in gem5 discussion.
Add link to the gem5 discussion

2024-09-03 20:34 UTC, erin-le commented on src/ubuntu-generic-diskimages/README.md
>  **Note:** the `x86-ubuntu-with-kvm.py` script requires a host machine with KVM to function correctly.
```suggestion
**Note:** the `x86-ubuntu-with-kvm.py` script requires a x86 host machine with KVM to function correctly.
```

2024-09-03 20:34 UTC, erin-le commented on src/ubuntu-generic-diskimages/README.md
> +**Note:** the `arm-ubuntu-run-with-kvm.py` script requires a host machine with KVM to function correctly.
```suggestion
**Note:** the `arm-ubuntu-run-with-kvm.py` script requires an Arm host machine with KVM to function correctly.
```

2024-09-03 21:24 UTC, erin-le commented on src/ubuntu-generic-diskimages/BUILDING.md
> +dd if=/dev/zero of=flash0.img bs=1M count=64
Can the commands to get flash0.img be incorporated into build-arm.sh and/or be mentioned in the "## Disk Image" section of the document? These are listed after information about how to customize the disk image, so it may be difficult for users to figure out that they need to do this.

2024-09-03 21:27 UTC, erin-le commented on src/ubuntu-generic-diskimages/BUILDING.md
> +Building the arm image assume that we are on an ARM machine as we use kvm to build the image.
Add info about how to build Arm disk images without using KVM

2024-09-04 18:22 UTC, erin-le commented on src/ubuntu-generic-diskimages/README.md
> +```
These example scripts show how to run the workload and not how to set up a simulation with a disk image, kernel, and bootloader. I think it is helpful to point the user to the example scripts, but you should also add instructions on how to use `set_kernel_disk_workload` with the disk image the user built.

2024-09-04 18:52 UTC, erin-le commented on src/ubuntu-generic-diskimages/README.md
> +```
Here's the chunk of code I used for Arm:

```
disk_img = DiskImageResource("/path/to/disk/image/directory/arm-disk-image-22-04/arm-ubuntu", root_partition="2")
board.set_kernel_disk_workload(
        disk_image=disk_img,
        bootloader=obtain_resource("arm64-bootloader-foundation"),
        kernel=obtain_resource("arm64-linux-kernel-5.15.36")
    )
```

2024-09-05 16:49 UTC, Harshil2107 commented on src/ubuntu-generic-diskimages/BUILDING.md
> +To take a pre-built image and add new files or packages, see the post in gem5 discussion.
I added the link to the documentation but it is still in PR form, the link should work as soon as it is merged.

2024-09-05 16:51 UTC, Harshil2107 commented on src/ubuntu-generic-diskimages/BUILDING.md
> +dd if=/dev/zero of=flash0.img bs=1M count=64
Moved the section to the `## Disk Image` section.

2024-09-11 23:35 UTC, erin-le commented on src/ubuntu-generic-diskimages/build-arm.sh
> +
```suggestion

# Get flash0.img
cd files

dd if=/dev/zero of=flash0.img bs=1M count=64
dd if=/usr/share/qemu-efi-aarch64/QEMU_EFI.fd of=flash0.img conv=notrunc

cd ..

```

2024-09-12 01:02 UTC, erin-le submitted a review, later dismissed
LGTM. I tested building and using the disk images as resources in a simulation and they all work. Thanks for all of the changes!

2024-09-12 21:48 UTC, powerjg commented on src/ubuntu-generic-diskimages/scripts/post-installation.sh
>  mv /usr/local/bin/m5 /usr/local/bin/gem5-bridge
Line 80 below is wrong. It says "x86-ubuntu.pkr.hcl"

2024-09-12 21:50 UTC, powerjg commented on src/ubuntu-generic-diskimages/README.md
> +If you want to enable networking, you need to modify the disk image and move the file `/etc/netplan/00-installer-config.yaml.bak` or `/etc/netplan/50-cloud-init.yaml.bak` to `/etc/netplan/00-installe
Above this on line 17, it says "The headers for `libm5` are installed in `/usr/local/include/gem5-bridge`" that should be "The headers for `libm5` are installed in `/usr/local/include`"

2024-09-13 17:33 UTC, powerjg approved these changes

2024-09-13 17:41 UTC, merged