resources: Makefiles to build GPUFS apps using docker
gem5/gem5-resources pull request #39
Opened 2024-06-06 16:40 UTC by abmerop

Add Makefile.default for everything except HACC and DNNMark. These can be used with:

docker run <flags> ghcr.io/gem5/gpu-fs:latest make -f Makefile.default

2024-06-06 16:40 UTC, abmerop commented
- This is on develop because it depends on https://github.com/gem5/gem5-resources/pull/22
- We should discuss how to handle the README.md for this without it getting lost in SE mode details
- Main changes:
   - hipcc path has changes since ROCm 4.
   - New hipcc has an absurd amount of warning due to ignoring return value of hip*. Should we add -Wno-unused-result to the Makefile?
   - Make clean attempts to not clobber and SE mode makefile binaries but maybe there is a better approach
- This does not include HACC or DNNMark
   - I have *NO* idea how you are supposed to build HACC
   - DNNMark requires changes to the GPUFS build docker image and some code changes but I eventually got it to work. I do not have a machine with gtest to run the apps though.

2024-06-06 17:13 UTC, mattsinc commented
> his does not include HACC or DNNMark:
> 
>     * I have _NO_ idea how you are supposed to build HACC.
> 
>     * DNNMark requires changes to the GPUFS build docker image and some code changes but I eventually got it to work. I do not have a GPU machine with gtest to run the apps though.

In regards to HACC: you have to build its special Dockerfile first, then run make (although I vaguely recall you changed that in the past?).

Yes, we should add that warning flag.

Sure we could have separate bin directories for FS and SE mode.

2024-06-06 17:20 UTC, mattsinc commented on src/gpu/pannotia/bc/Makefile.default
> +OPTS = -O3
are you seeing that BC passes with O3 on real GPUs now?  It was O1 before because of some sort of compilation error with ROCm 4 (maybe fixed?).  But this is a place where SE and FS may have to diverge -- since SE supports ROCm 4 at the moment.

2024-06-06 17:20 UTC, mattsinc commented on src/gpu/pannotia/bc/Makefile.default
> +HIP_PATH ?= /opt/rocm
with Pannotia the Makefile.default was intended for compiling on the real GPU and Makefile.gem5-fusion was for gem5.  This change seems to be altering that, which means gem5's Makefiles would no longer be directly compatible with the non-gem5 Makefiles for Pannotia.  I guess we should discuss if that is a dealbreaker or not...

2024-06-06 17:20 UTC, mattsinc commented on src/gpu/pannotia/color/Makefile.default
> +MAX_CPP = coloring_max.cpp
This isn't the end of the world, and it might even be for the better, but there was an explicit intent in forcing the user to pick what binary they wanted previously whereas now they get all of them.  I think I'm in favor of the change though ...

2024-06-06 17:20 UTC, mattsinc commented on src/gpu/pennant/src/HydroGPU.cxx
> +#ifndef ATOMIC_MIN_DEFINED
Shouldn't this be ifdef?

2024-06-06 17:27 UTC, abmerop commented
> In regards to HACC: you have to build its special Dockerfile first, then run make (although I vaguely recall you changed that in the past?).

I am trying to build on real hardware. Even after setting all the environment variables in the dockerfile it doesn't work.  I did not make that change btw, so not taking credit for it.

> Yes, we should add that warning flag.

Done

> Sure we could have separate bin directories for FS and SE mode.

Done

2024-06-06 17:33 UTC, abmerop commented on src/gpu/pannotia/color/Makefile.default
> +MAX_CPP = coloring_max.cpp
What is the benefit of forcing them to pick?  If needed the default make target can change.  I strongly dislike the previous approach of needing to edit the makefile to change the variant though.

2024-06-06 17:33 UTC, abmerop commented on src/gpu/pannotia/bc/Makefile.default
> +HIP_PATH ?= /opt/rocm
I tested all of these to make sure they build and run on hardware.  The path changed in ROCm 5 I think, so unless you have some ancient version of ROCm this will compile on a real GPU.  The gem5 makefiles specific to SE mode are untouched here and still use the old path.

2024-06-06 17:33 UTC, abmerop commented on src/gpu/pennant/src/HydroGPU.cxx
> +#ifndef ATOMIC_MIN_DEFINED
I negated this to avoid touching SE mode make files.  atomicMin was added in some HIP version since ROCm 4, so keeping this results in duplicate symbols when linking.  I define this in makefile.default to build on modern ROCm versions.

2024-06-06 17:34 UTC, abmerop commented on src/gpu/pannotia/bc/Makefile.default
> +OPTS = -O3
Actually this one crashes in the parseCOO function in `_IO_fgets` which will be fun to debug.  So I wasn't actually able to test this.  Every other app works though and I would be surprised if whatever the bug was here still exists in ROCm 6.1.  I have built the rest of the benchmarks on real silicon and ran them and got correct results.

2024-06-06 18:21 UTC, mattsinc commented on src/gpu/pannotia/color/Makefile.default
> +MAX_CPP = coloring_max.cpp
you didn't need to edit the Makefile, you just needed to set a variable on the command line (export VARIANT=...) but I agree picking is not necessary.

2024-06-06 18:23 UTC, mattsinc commented on src/gpu/pannotia/bc/Makefile.default
> +HIP_PATH ?= /opt/rocm
Interesting, maybe I am misunderstanding.  I thought you intended the Makefile.default's to be the default Makefile for all gem5 GPUFS files?  If so, I had assumed you would need to be including m5ops and the like somewhere in the linkage for the Makefile.default's, but since that isn't the case maybe you intend Makefile.default to be for running on the real GPU?  Sorry if I'm missing something dumb here.

2024-06-06 18:23 UTC, mattsinc commented on src/gpu/pannotia/bc/Makefile.default
> +OPTS = -O3
Should we revert to O1 then?  I believe this is the same bug I was getting ...

2024-06-06 18:25 UTC, abmerop commented on src/gpu/pannotia/bc/Makefile.default
> +HIP_PATH ?= /opt/rocm
Oh, I see. So this does work with -O1.  The previous comment was a bit misleading because it is not a compile error and seems unrelated to GPUs since it crashes in fgets().  I changed this back to -O1 and reworded the comment.

2024-06-06 18:46 UTC, abmerop commented on src/gpu/pannotia/bc/Makefile.default
> +HIP_PATH ?= /opt/rocm
The goal of GPUFS is to run unmodified binaries, so the makefile for GPUFS and makefile for a real system would be identical

2024-06-06 18:55 UTC, mattsinc commented on src/gpu/pannotia/bc/Makefile.default
> +HIP_PATH ?= /opt/rocm
But how are you handling the m5ops in those files?  Those will not work on the real GPU.

2024-06-06 21:58 UTC, abmerop commented
I've added `Makefile.gpufs` to handle the m5ops.  These only exist in pannotia so only pannotia has these.  `Makefile.default` now builds for the host only.  For all of the other resources, `Makefile.default` should be used to run in GPUFS.

One other thing, I am not sure about what to do with the buildall.sh script in pannotia. It seems to only build the gem5-fusion target and there are now three targets (gem5-fusion, default, gpufs).

2024-06-07 01:35 UTC, mattsinc commented
> I've added `Makefile.gpufs` to handle the m5ops. These only exist in pannotia so only pannotia has these. `Makefile.default` now builds for the host only. For all of the other resources, `Makefile.default` should be used to run in GPUFS.
> 
> One other thing, I am not sure about what to do with the buildall.sh script in pannotia. It seems to only build the gem5-fusion target and there are now three targets (gem5-fusion, default, gpufs).

we could rename buildall.sh to buildall-gem5fusion.sh?  And add buildall-gpufs.sh?

2024-06-07 01:35 UTC, mattsinc commented on src/gpu/pannotia/bc/Makefile.default
> +OPTS = -O3
Just making sure you didn't miss my reply here

2024-06-07 15:18 UTC, abmerop commented
> we could rename buildall.sh to buildall-gem5fusion.sh? And add buildall-gpufs.sh?

The current behavior is `./buildall.sh` will build Makefile.default, and `./buildall.sh foo` will build gem5-fusion with `extraparams=foo`. We could probably modify it to allow you to select the target. As it is right now, it is selecting gpufs build for some reason. I don't know how make selects which target to build.

What i'd propose is making the `$1` be the makefile target (default, gem5-fusion, or gpufs) and `$2` be the extraparam.  If no option it would be either an error or Makefile.default.

2024-06-07 17:46 UTC, mattsinc commented
> > we could rename buildall.sh to buildall-gem5fusion.sh? And add buildall-gpufs.sh?
> 
> The current behavior is `./buildall.sh` will build Makefile.default, and `./buildall.sh foo` will build gem5-fusion with `extraparams=foo`. We could probably modify it to allow you to select the target. As it is right now, it is selecting gpufs build for some reason. I don't know how make selects which target to build.
> 
> What i'd propose is making the `$1` be the makefile target (default, gem5-fusion, or gpufs) and `$2` be the extraparam. If no option it would be either an error or Makefile.default.

This makes sense to me

2024-06-07 17:50 UTC, mattsinc requested changes

2024-06-07 17:50 UTC, mattsinc commented on src/gpu/pannotia/bc/BC.cpp
> +    map_m5_mem();
Do you need to add the "magic" address here too?

(same question for all Pannotia apps, but not going to add every single one as a comment)

2024-06-07 17:50 UTC, mattsinc commented on src/gpu/pannotia/bc/Makefile.default
> +OPTS = -O3
I see you updated this, so resolving

2024-06-07 18:35 UTC, abmerop commented on src/gpu/pannotia/bc/BC.cpp
> +    map_m5_mem();
Sigh.  Yes.  It looks like the default was changed to zero so I guess I have to build in the m5_mmap file which I'm going to guess will cause a duplicate linker error because it's linked into the libm5.a...  There doesn't appear to be a way to set the value when scons'ing the library either.  I don't know how this was ever supposed to work.

2024-06-07 19:04 UTC, abmerop commented on src/gpu/pannotia/bc/BC.cpp
> +    map_m5_mem();
Figured that out and made the buildall change as well, which involved a few other fixes.

2024-06-07 20:34 UTC, mattsinc approved these changes

2024-06-14 21:03 UTC, merged