resources: Change pannotia to fopen from fstream
gem5/gem5-resources pull request #44
Opened 2024-07-11 22:13 UTC by mattsinc

A recent commit (b17de69) changed Pannotia's parser to use fstream instead of fgets. However, this change introduces a "bad_alloc" error with some versions of ROCm. To resolve this, change Pannotia's parse to use fopen instead, which works for both GPUSE and GPUFS in our testing.

The was done by @jebraun3 but I am pushing to resolve problem affecting all Pannotia (weekly) tests.

2024-07-11 22:13 UTC, mattsinc commented
@abmerop : I checked and FW, which uses a different parsing function, appears to already use fopen: https://github.com/gem5/gem5-resources/blob/stable/src/gpu/pannotia/fw/parse.cpp#L35

So I think it doesn't need to be changed ...

2024-07-11 22:40 UTC, abmerop commented
It seems that #24 fixes GPUFS but breaks SE (the current issue). This effectively reverts #24 and breaks GPUFS but fixes SE.  I believe FW works on both.  We should try and figure out what FW is doing and replicate that? 

For reference getline() hangs / crashes in ROCm 6+.  The fgets() in FW seems to work fine on both though.

2024-07-11 22:40 UTC, abmerop requested changes
gfets instead of getline .

2024-07-12 01:50 UTC, mattsinc commented
> It seems that #24 fixes GPUFS but breaks SE (the current issue). This effectively reverts #24 and breaks GPUFS but fixes SE. I believe FW works on both. We should try and figure out what FW is doing and replicate that?
> 
> For reference getline() hangs / crashes in ROCm 6+. The fgets() in FW seems to work fine on both though.

I don't think changing back to fgets (which I think is what you're asking) makes sense because that is what you originally changed it from, right?

Maybe this is a fundamental ROCm 4 vs. 6 thing and we need to have an ifdef controlling which is used for now?

2024-07-12 15:54 UTC, abmerop commented
> > It seems that #24 fixes GPUFS but breaks SE (the current issue). This effectively reverts #24 and breaks GPUFS but fixes SE. I believe FW works on both. We should try and figure out what FW is doing and replicate that?
> > For reference getline() hangs / crashes in ROCm 6+. The fgets() in FW seems to work fine on both though.
> 
> I don't think changing back to fgets (which I think is what you're asking) makes sense because that is what you originally changed it from, right?
> 
> Maybe this is a fundamental ROCm 4 vs. 6 thing and we need to have an ifdef controlling which is used for now?

I believe one calls the other.  Let me try this again because I just noticed you are getline'ing into a nullptr. Maybe it works if `line` is allocated.

2024-07-12 18:00 UTC, mattsinc commented
> > > It seems that #24 fixes GPUFS but breaks SE (the current issue). This effectively reverts #24 and breaks GPUFS but fixes SE. I believe FW works on both. We should try and figure out what FW is doing and replicate that?
> > > For reference getline() hangs / crashes in ROCm 6+. The fgets() in FW seems to work fine on both though.
> > 
> > 
> > I don't think changing back to fgets (which I think is what you're asking) makes sense because that is what you originally changed it from, right?
> > Maybe this is a fundamental ROCm 4 vs. 6 thing and we need to have an ifdef controlling which is used for now?
> 
> I believe one calls the other. Let me try this again because I just noticed you are getline'ing into a nullptr. Maybe it works if `line` is allocated.

I believe we passed a NULL string into getline because that was what the man page recommended, but I can't seem to find it.  @jebraun3 if you see this and remember, your input would be appreciated :)

The C++ page on getline is not helpful: https://cplusplus.com/reference/string/string/getline/, although it does show passing a string in instead of char * -- maybe we should switch and see if the C++ string library handles the issue under the hood?

2024-07-12 18:06 UTC, abmerop commented
> > > 
> > > 
> > > I don't think changing back to fgets (which I think is what you're asking) makes sense because that is what you originally changed it from, right?
> > > Maybe this is a fundamental ROCm 4 vs. 6 thing and we need to have an ifdef controlling which is used for now?
> > 
> > 
> > I believe one calls the other. Let me try this again because I just noticed you are getline'ing into a nullptr. Maybe it works if `line` is allocated.
> 
> I believe we passed a NULL string into getline because that was what the man page recommended, but I can't seem to find it. @jebraun3 if you see this and remember, your input would be appreciated :)
> 
> My recollection though was if a string exceeded the allocated char * size, then it was causing a failure and James and I had found something online saying that a NULL char * should be passed in instead ...
> 
> The C++ page on getline is not helpful: https://cplusplus.com/reference/string/string/getline/, although it does show passing a string in instead of char * -- maybe we should switch and see if the C++ string library handles the issue under the hood?

I see. Allocating also doesn't work unfortunately.  So either we need to find a way to read a file that works for both modes or ifdef for GEM5_FUSION vs. GEM5_FS. It might make sense to have completely separate files and ifdef the include given the amount of changes.

2024-07-12 18:10 UTC, mattsinc commented
> > > > I don't think changing back to fgets (which I think is what you're asking) makes sense because that is what you originally changed it from, right?
> > > > Maybe this is a fundamental ROCm 4 vs. 6 thing and we need to have an ifdef controlling which is used for now?
> > > 
> > > 
> > > I believe one calls the other. Let me try this again because I just noticed you are getline'ing into a nullptr. Maybe it works if `line` is allocated.
> > 
> > 
> > I believe we passed a NULL string into getline because that was what the man page recommended, but I can't seem to find it. @jebraun3 if you see this and remember, your input would be appreciated :)
> > My recollection though was if a string exceeded the allocated char * size, then it was causing a failure and James and I had found something online saying that a NULL char * should be passed in instead ...
> > The C++ page on getline is not helpful: https://cplusplus.com/reference/string/string/getline/, although it does show passing a string in instead of char * -- maybe we should switch and see if the C++ string library handles the issue under the hood?
> 
> I see. Allocating also doesn't work unfortunately. So either we need to find a way to read a file that works for both modes or ifdef for GEM5_FUSION vs. GEM5_FS. It might make sense to have completely separate files and ifdef the include given the amount of changes.

If you change it to a string instead of a char *, does it work on your end?

2024-07-13 00:18 UTC, abmerop commented
This seems to be another bizarre compiler bug involving optimization. I made the following `Makefile.default` change to get `mis` to work natively.  The same GPUFS bug happens natively and it's faster to iterate natively, hence starting with that.  

**My suggestion is to go with this PR as it is now and add a commit changing all of the `Makefile.default` and `Makefile.gpufs` files.** I will test other pannotia bmks while waiting for feedback.

```--- a/src/gpu/pannotia/mis/Makefile.default
+++ b/src/gpu/pannotia/mis/Makefile.default
@@ -10,7 +10,9 @@ BIN_DIR ?= ./bin.default
 all: $(BIN_DIR)/$(EXECUTABLE)

 $(BIN_DIR)/$(EXECUTABLE): $(CPPSRC) ../graph_parser/parse.cpp ../graph_parser/util.cpp $(BIN_DIR)
-       $(HIPCC) $(OPTS) --offload-arch=gfx900,gfx90a,gfx942 $(CXXFLAGS) ../graph_parser/parse.cpp ../graph_parser/util.cpp $(CPPSRC) -o $(BIN_DIR)/$(EXECUTABLE)
+       $(HIPCC) -O0 --offload-arch=gfx900,gfx90a,gfx942 $(CXXFLAGS) ../graph_parser/parse.cpp -o $(BIN_DIR)/parse.o -c
+       $(HIPCC) -O0 --offload-arch=gfx900,gfx90a,gfx942 $(CXXFLAGS) ../graph_parser/util.cpp -o $(BIN_DIR)/util.o -c
+       $(HIPCC) $(OPTS) --offload-arch=gfx900,gfx90a,gfx942 $(CXXFLAGS) $(BIN_DIR)/parse.o $(BIN_DIR)/util.o $(CPPSRC) -o $(BIN_DIR)/$(EXECUTABLE)

 $(BIN_DIR):
        mkdir -p $(BIN_DIR)
```

Same change to `Makefile.gpufs`. **No** changes to `Makefile.gem5-fusion` (SE mode). Basically, build the parser with `-O0` and GPU code with `-O3`.  I am fine with this solution as CPU code is not ROI.

Interestingly enough, I was also able to get it to work with -O3 by enabling VERBOSE.  The extra printf added there seems to be enough to fix what appears to be a race condition between a futex being created and used. But that is getting outside of my wheelhouse.

2024-07-13 03:54 UTC, mattsinc commented
> This seems to be another bizarre compiler bug involving optimization. I made the following `Makefile.default` change to get `mis` to work natively. The same GPUFS bug happens natively and it is faster to iterate natively, hence starting with that.
> 
> **My suggestion is to go with this PR as it is now and add a commit changing all of the `Makefile.default` and `Makefile.gpufs` files.** I will test other pannotia bmks while waiting for feedback.
> 
> ```
> +++ b/src/gpu/pannotia/mis/Makefile.default
> @@ -10,7 +10,9 @@ BIN_DIR ?= ./bin.default
>  all: $(BIN_DIR)/$(EXECUTABLE)
> 
>  $(BIN_DIR)/$(EXECUTABLE): $(CPPSRC) ../graph_parser/parse.cpp ../graph_parser/util.cpp $(BIN_DIR)
> -       $(HIPCC) $(OPTS) --offload-arch=gfx900,gfx90a,gfx942 $(CXXFLAGS) ../graph_parser/parse.cpp ../graph_parser/util.cpp $(CPPSRC) -o $(BIN_DIR)/$(EXECUTABLE)
> +       $(HIPCC) -O0 --offload-arch=gfx900,gfx90a,gfx942 $(CXXFLAGS) ../graph_parser/parse.cpp -o $(BIN_DIR)/parse.o -c
> +       $(HIPCC) -O0 --offload-arch=gfx900,gfx90a,gfx942 $(CXXFLAGS) ../graph_parser/util.cpp -o $(BIN_DIR)/util.o -c
> +       $(HIPCC) $(OPTS) --offload-arch=gfx900,gfx90a,gfx942 $(CXXFLAGS) $(BIN_DIR)/parse.o $(BIN_DIR)/util.o $(CPPSRC) -o $(BIN_DIR)/$(EXECUTABLE)
> 
>  $(BIN_DIR):
>         mkdir -p $(BIN_DIR)
> ```
> 
> Same change to `Makefile.gpufs`. **No** changes to `Makefile.gem5-fusion` (SE mode). Basically, build the parser with `-O0` and GPU code with `-O3`. I am fine with this solution as CPU code is not ROI.
> 
> Interestingly enough, I was also able to get it to work with -O3 by enabling VERBOSE. The extra printf added there seems to be enough to fix what appears to be a race condition between a futex being created and used. But that is getting outside of my wheelhouse.

Just to be clear, you want me to make this change to the Makefile's as part of this commit (or an additional commit in this pull request)?

2024-07-13 18:56 UTC, abmerop commented
I can make the change as an additional commit or a new PR.  I'll approve and if you merge i'll take that as I should make another PR.

2024-07-13 18:56 UTC, abmerop approved these changes

2024-07-13 19:20 UTC, mattsinc commented
> I can make the change as an additional commit or a new PR. I'll approve and if you merge i'll take that as I should make another PR.

ok, either way would have been fine, but will go with your plan

2024-07-13 19:20 UTC, merged

2024-07-13 19:39 UTC, abmerop commented
This is better actually:  will fix our CI and if gem5 tests them, those too.

2024-07-14 15:54 UTC, abmerop commented
One final thought: Our SE mode CI tests are passing now, thanks for the PR.

2024-07-15 01:51 UTC, mattsinc commented
> One final thought: Our SE mode CI tests are passing now, thanks for the PR.

Progress, great -- nice job @jebraun3 !