resources: Update pannotia Makefiles for GPUFS/HW
gem5/gem5-resources pull request #45
Opened 2024-07-19 21:26 UTC by abmerop

There is an issue with the compiler used with GPUFS and hardware that causes a hang or crash in fstream. PR #44 changed fstream to fopen as fstream has similar issues in ROCm 4.0. To compromise and support both versions, this PR updates the GPUFS and hardware (Makefile.default) Makefiles to build the input parser with optimizations off (-O0) which "solves" the issue. Since we typically do not care about simulation time of reading input files, this seems like a decent compromise.

The GPUFS Makefiles also change the GEM5_PATH environment variable to GEM5_ROOT to be consistent with each Makefile.gem5-fusion.

The BC application is unchanged as it implements its open parser in its header file which cannot be compiled to an object file without refactoring the benchmark.

2024-07-20 04:16 UTC, mattsinc requested changes
Two questions:

1.  Does BC just not work in this version?
2.  Is there a wrapper Makefile above these that sets GEM5_ROOT, or do we expect users to set it?

2024-07-20 04:16 UTC, mattsinc commented on src/gpu/pannotia/mis/Makefile.default
> +    # There is a futex issue in hipcc with the graph parser. Compile without opts until this is fixed.
indented at different levels? (lines 13 vs. 14-16)

2024-07-20 04:16 UTC, mattsinc commented on src/gpu/pannotia/pagerank/Makefile.default
> +    # There is a futex issue in hipcc with the graph parser. Compile without opts until this is fixed.
same here

2024-07-20 04:16 UTC, mattsinc commented on src/gpu/pannotia/sssp/Makefile.default
> +    # There is a futex issue in hipcc with the graph parser. Compile without opts until this is fixed.
same here

2024-07-20 04:16 UTC, mattsinc commented on src/gpu/pannotia/sssp/Makefile.default
> +    # There is a futex issue in hipcc with the graph parser. Compile without opts until this is fixed.
same here

2024-07-20 04:16 UTC, mattsinc commented on src/gpu/pannotia/sssp/Makefile.gpufs
> +    # There is a futex issue in hipcc with the graph parser. Compile without opts until this is fixed.
same here (going to stop commenting on this here)

2024-07-22 21:39 UTC, abmerop commented
> Two questions:
> 
> 1. Does BC just not work in this version?
> 2. Is there a wrapper Makefile above these that sets GEM5_ROOT, or do we expect users to set it?

BC works.  The current solution is to build with `-O1`.

GEM5_ROOT needs to be set by the user.  I guess a reasonable default could be `../../../../gem5` though (assumes a base directory containing gem5 repo and gem5-resources repo).

2024-07-25 01:38 UTC, mattsinc commented
> > Two questions:
> > 
> > 1. Does BC just not work in this version?
> > 2. Is there a wrapper Makefile above these that sets GEM5_ROOT, or do we expect users to set it?
> 
> BC works. The current solution is to build with `-O1`.
> 
> GEM5_ROOT needs to be set by the user. I guess a reasonable default could be `../../../../gem5` though (assumes a base directory containing gem5 repo and gem5-resources repo).

Right, the old Makefiles used:

GEM5_PATH ?= ...

To allow the users to have this set already, but guess something otherwise.  I think your change makes it so this is essentially not done now, and the user needs to look at this and guess?

2024-07-25 14:47 UTC, abmerop commented
> 
> Right, the old Makefiles used:
> 
> GEM5_PATH ?= ...
> 
> To allow the users to have this set already, but guess something otherwise. I think your change makes it so this is essentially not done now, and the user needs to look at this and guess?

I added a default `GEM5_ROOT ?= ../../../../../gem5` .  I assume you meant `GEM5_ROOT` rather than `GEM5_PATH`. I am using the same variable as in each `Makefile.gem5-fusion`.

2024-07-25 22:38 UTC, mattsinc commented
> > Right, the old Makefiles used:
> > GEM5_PATH ?= ...
> > To allow the users to have this set already, but guess something otherwise. I think your change makes it so this is essentially not done now, and the user needs to look at this and guess?
> 
> I added a default `GEM5_ROOT ?= ../../../../../gem5` . I assume you meant `GEM5_ROOT` rather than `GEM5_PATH`. I am using the same variable as in each `Makefile.gem5-fusion`.

The old versions were using GEM5_PATH instead, but GEM5_ROOT is ok.

2024-07-25 22:39 UTC, mattsinc approved these changes

2024-07-25 23:12 UTC, abmerop commented
> The old versions were using GEM5_PATH instead, but GEM5_ROOT is ok.

It looks like the READMEs were updated in #15 to say GEM5_ROOT, so I will keep that

2024-07-26 02:08 UTC, mattsinc commented
> > The old versions were using GEM5_PATH instead, but GEM5_ROOT is ok.
> 
> It looks like the READMEs were updated in #15 to say GEM5_ROOT, so I will keep that

That was probably not intentional, but is fine.

2024-07-26 02:10 UTC, merged