Develop
gem5/gem5-resources pull request #5
Opened 2023-08-15 23:04 UTC by jebraun3

Adding mmap support to FW and bug fixes

2023-08-15 23:13 UTC, mattsinc requested changes
Looks like these lines need tabs removed and converted to spaces in a bunch of places, including non-marked lines.

2023-08-15 23:13 UTC, mattsinc commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
> +	char *tmpchar;
Looks like these lines need tabs removed and converted to spaces.

2023-08-15 23:13 UTC, mattsinc commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
> +	int * distmatrix = NULL;
Looks like these lines need tabs removed and converted to spaces.

2023-08-15 23:13 UTC, mattsinc commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
> +		tmpchar = argv[1];  // Graph input file
Looks like these lines need tabs removed and converted to spaces.

2023-08-15 23:13 UTC, mattsinc commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
> +			create_mmap = true;
Looks like these lines need tabs removed and converted to spaces.

2023-08-15 23:13 UTC, mattsinc commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
> +        fprintf(stderr, "You did something wrong!\n");
Looks like these lines need tabs removed and converted to spaces.

2023-08-15 23:14 UTC, mattsinc commented
This goes https://github.com/gem5/gem5/pull/186/

2023-08-15 23:16 UTC, mattsinc commented on src/gpu/pannotia/fw/README.md
> +## Compiling GCN3_X86/gem5.opt
Please update this part and the subsequent parts to explain the new command line options for make'ing with/without/etc. mmap.

2023-08-16 14:30 UTC, powerjg requested changes

2023-08-16 14:30 UTC, powerjg commented on src/gpu/pannotia/fw/README.md
This shows that every line in the file has changed, but I think it's all whitespace changes. Could you either revert the whitespace changes or let us know the reason for the whitespace changes (e.g., if the previous file was using windows line endings then it would be appropriate to update them to use newlines).

2023-08-16 14:32 UTC, powerjg commented
@mattsinc I'm going to assign this PR to you. As a reminder, being assignmed means that you are responsible to make sure that there is progress made on the PR and you can merge it when it's ready.

Thanks for the help!

2023-08-17 15:18 UTC, mattsinc reviewed
@jebraun3 I know you said you have one more change to push, and @powerjg 's comment below remains.

2023-08-17 15:18 UTC, mattsinc commented on src/gpu/pannotia/fw/README.md
@jebraun3 I am not sure what you did here, please chime in

2023-08-22 05:23 UTC, mattsinc commented
@jebraun3 just checking in on this

2023-08-22 23:14 UTC, mattsinc requested changes

2023-08-22 23:14 UTC, mattsinc commented on src/gpu/pannotia/fw/README.md
> +```
Update this to include a sentence explaining that this can be run in gem5, but we recommend running on the real CPU.  And then update line 52 to reflect how to run it on the real CPU.

2023-08-22 23:14 UTC, mattsinc commented on src/gpu/pannotia/fw/README.md
> +# Create a mmapped input file
Create --> Generate to be consistent with what you say on line 57.

2023-08-23 03:42 UTC, jebraun3 commented on src/gpu/pannotia/fw/README.md
It was windows line endings which are being reverted. The same thing appears to be happening in Floyd-Warshall.cpp too, so I will revert those changes too.

2023-08-29 05:24 UTC, BobbyRBruce commented
Is this done and ready for another view?

2023-08-29 18:09 UTC, jebraun3 commented
Yes, it is ready.

2023-08-29 19:01 UTC, mattsinc requested changes
A few minor changes to be made, but overall looks good!

2023-08-29 19:01 UTC, mattsinc commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
> +	   fprintf(stderr, "SWITCHES\n    -f [file name]\n            input file name\n");
Either lines 115-117 are not indented as far as the subsequent 3 lines, or the subsequent 3 lines are indented one space too much

(looks like 115-117 are the issue)

2023-08-29 19:01 UTC, mattsinc commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
> +	    // TODO: Print help string here
TODO should be removed

2023-08-29 19:01 UTC, mattsinc commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
> +        fprintf(stderr, "Ignoring error checking\n");
This should probably be a print to stdout instead, and it should be a warning or something like that -- there is nothing wrong with this combo, the print is more like an FYI

2023-08-29 19:01 UTC, mattsinc commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
> +        fprintf(stderr, "Ignoring input file\n");
Same here

2023-08-29 19:01 UTC, mattsinc commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
line 184 can probably be removed?

2023-08-29 19:01 UTC, mattsinc commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
> +
extra spaces, remove

2023-08-29 19:01 UTC, mattsinc commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
> +
extra spaces, remove

2023-08-29 19:01 UTC, mattsinc commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
> +    }
extra space, remove

2023-08-29 19:01 UTC, mattsinc commented on src/gpu/pannotia/fw/README.md
> +docker run --rm -v ${PWD}:${PWD} -w ${PWD} -u $UID:$GID gcr.io/gem5-test/gcn-gpu make gem5-fusion; make default
What is make default for?

2023-08-29 23:33 UTC, jebraun3 commented on src/gpu/pannotia/fw/README.md
> +docker run --rm -v ${PWD}:${PWD} -w ${PWD} -u $UID:$GID gcr.io/gem5-test/gcn-gpu make gem5-fusion; make default
It is for generating mmapped input files on the actual CPU

2023-08-31 02:19 UTC, jebraun3 commented
Resolved the spacing issues from above

2023-08-31 04:49 UTC, mattsinc requested changes
Thanks!  Getting closer, almost there!

2023-08-31 04:49 UTC, mattsinc commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
> +        fprintf(stdout, "Ignoring error checking\n");
Looks like this remains:

This should probably be a print to stdout instead, and it should be a warning or something like that -- there is nothing wrong with this combo, the print is more like an FYI

2023-08-31 04:49 UTC, mattsinc commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
> +        fprintf(stdout, "Ignoring input file\n");
This looks like it remains too:

This should probably be a print to stdout instead, and it should be a warning or something like that -- there is nothing wrong with this combo, the print is more like an FYI

2023-09-05 20:22 UTC, powerjg reviewed
Just need to resolve the last couple of items.

Also, we would **strongly encourage** you to create all of the *resources* (e.g., executable binary files used by gem5 and files used by the workloads) and send them to us so we can host them on `dist.gem5.org`. This way, you do not have to build them to run tests.

If the above is impossible, I would like to understand why.

2023-09-05 20:22 UTC, powerjg commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
> +        fprintf(stdout, "Ignoring error checking\n");
Is this resolved (I'm not sure what the original code looked like).

BTW, why are you using `fprintf` instead of `std::cout <<` or `std::cerr << `? You don't have to make a change, but it's quite strange to use `fprintf` in C++ code.

2023-09-05 20:22 UTC, powerjg commented on src/gpu/pannotia/fw/README.md
> +docker run --rm -v ${PWD}:${PWD} -w ${PWD} -u $UID:$GID --memory="${docker_mem_limit}" hacc-test-weekly bash -c "./gem5-resources/src/gpu/pannotia/fw/bin/fw_hip -f ./gem5-resources/src/gpu/pannotia/f
This docker image is incorrect. It should probably be `gcr.io/gem5-test/gcn-gpu`, but I don't really know why this command needs to run in docker.

2023-09-09 01:42 UTC, mattsinc commented
> Just need to resolve the last couple of items.
> 
> Also, we would **strongly encourage** you to create all of the _resources_ (e.g., executable binary files used by gem5 and files used by the workloads) and send them to us so we can host them on `dist.gem5.org`. This way, you do not have to build them to run tests.
> 
> If the above is impossible, I would like to understand why.

We can certainly work with you to add resources there, but I don't recall this ever being a requirement before.  In any event, I believe both building and resources should be options, since people may want to change the application locally and still use it.

2023-09-09 01:43 UTC, mattsinc commented on src/gpu/pannotia/fw/README.md
> +docker run --rm -v ${PWD}:${PWD} -w ${PWD} -u $UID:$GID --memory="${docker_mem_limit}" hacc-test-weekly bash -c "./gem5-resources/src/gpu/pannotia/fw/bin/fw_hip -f ./gem5-resources/src/gpu/pannotia/f
I can't seem to reply to the fprintf question straightaway, but I believe I suggested that because Shuai used that format originally in the benchmark and we were keeping things the same.

2023-09-09 01:44 UTC, mattsinc commented on src/gpu/pannotia/fw/README.md
> +docker run --rm -v ${PWD}:${PWD} -w ${PWD} -u $UID:$GID --memory="${docker_mem_limit}" hacc-test-weekly bash -c "./gem5-resources/src/gpu/pannotia/fw/bin/fw_hip -f ./gem5-resources/src/gpu/pannotia/f
In regard to the "is this resolved" comment, no it still needs to be to stderr instead of stdout.

2023-09-09 01:46 UTC, mattsinc commented on src/gpu/pannotia/fw/README.md
> +docker run --rm -v ${PWD}:${PWD} -w ${PWD} -u $UID:$GID --memory="${docker_mem_limit}" hacc-test-weekly bash -c "./gem5-resources/src/gpu/pannotia/fw/bin/fw_hip -f ./gem5-resources/src/gpu/pannotia/f
Finally, in regard to the "why docker" comment, I believe that is purely down to not being able to assume HIP is installed outside the docker.

2023-09-09 01:46 UTC, mattsinc commented on src/gpu/pannotia/fw/Floyd-Warshall.cpp
> +        fprintf(stdout, "Ignoring error checking\n");
Yes, this is resolved.

2023-09-09 01:48 UTC, mattsinc requested changes
@jebraun3 please make sure to address @powerjg 's comments (e.g., docker)

2023-09-11 21:22 UTC, mattsinc commented
@mkjost0 , @BobbyRBruce : how do you want us to send you an updated binary for FW?  Just compile locally and email you the binary?  Send instructions to you of how to compile it?  Leave it in a shared folder on loupe?

2023-09-11 21:56 UTC, jebraun3 commented
The docker image issue has been resolved

2023-09-11 22:55 UTC, powerjg commented
> We can certainly work with you to add resources there, but I don't recall this ever being a requirement before. In any event, I believe both building and resources should be options, since people may want to change the application locally and still use it.

Absolutely, I agree that end users should be able to build the resources. We should have enough documentation in the gem5-resources repo so that anyone can build the binary (preferably in a fully reproducible way).

However, we need to have a binary to test with. We don't want to build guest binaries during testing. Can you give @mkjost0 enough information to build the guest binary herself so we can upload it?

2023-09-11 22:56 UTC, powerjg commented on src/gpu/pannotia/fw/README.md
> +docker run --rm -v ${PWD}:${PWD} -w ${PWD} -u $UID:$GID --memory="${docker_mem_limit}" hacc-test-weekly bash -c "./gem5-resources/src/gpu/pannotia/fw/bin/fw_hip -f ./gem5-resources/src/gpu/pannotia/f
Why do you need HIP to generate the graph? As far as I can tell this doesn't use the GPU. 

All inputs to the test should be produced outside of the test and stored on dist.gem5.org. This includes guest binaries and inputs to those binaries.

2023-09-11 22:59 UTC, powerjg commented on src/gpu/pannotia/fw/README.md
> +docker run --rm -v ${PWD}:${PWD} -w ${PWD} -u $UID:$GID --memory="${docker_mem_limit}" gcr.io/gem5-test/gcn-gpu bash -c "./gem5-resources/src/gpu/pannotia/fw/bin/fw_hip -f ./gem5-resources/src/gpu/pa
What is `${docker_mem_limit}`? I don't see this specified in the readme.

2023-09-11 23:09 UTC, mattsinc commented on src/gpu/pannotia/fw/README.md
> +docker run --rm -v ${PWD}:${PWD} -w ${PWD} -u $UID:$GID --memory="${docker_mem_limit}" gcr.io/gem5-test/gcn-gpu bash -c "./gem5-resources/src/gpu/pannotia/fw/bin/fw_hip -f ./gem5-resources/src/gpu/pa
docker_mem_limit is from the weekly.sh script -- @jebraun3 that should be removed too

2023-09-11 23:10 UTC, mattsinc commented
> > We can certainly work with you to add resources there, but I don't recall this ever being a requirement before. In any event, I believe both building and resources should be options, since people may want to change the application locally and still use it.
> 
> Absolutely, I agree that end users should be able to build the resources. We should have enough documentation in the gem5-resources repo so that anyone can build the binary (preferably in a fully reproducible way).
> 
> However, we need to have a binary to test with. We don't want to build guest binaries during testing. Can you give @mkjost0 enough information to build the guest binary herself so we can upload it?

That is the intent of what we're trying to writeup here, unsuccessfully I guess.

2023-09-11 23:11 UTC, mattsinc commented on src/gpu/pannotia/fw/README.md
> +docker run --rm -v ${PWD}:${PWD} -w ${PWD} -u $UID:$GID --memory="${docker_mem_limit}" hacc-test-weekly bash -c "./gem5-resources/src/gpu/pannotia/fw/bin/fw_hip -f ./gem5-resources/src/gpu/pannotia/f
We can certainly add this to the resources in dist.gem5.org, but the goal of the documentation here is to explain how someone would do it for any arbitrary graph (e.g., because they want to use a different graph than the one we show as an example here).

2023-09-11 23:12 UTC, mattsinc requested changes
docker_mem_limit should be removed, along with anything @powerjg feels is unclear about the README explaining how to do this for a generic example.

2023-09-15 05:29 UTC, mattsinc commented
@jebraun3 just making sure you saw the above about the docker_mem_limit?

2023-09-15 17:34 UTC, jebraun3 commented
Yes, it has been removed. @powerjg is there anything else that is unclear or needs revision in the README?

2023-09-17 17:27 UTC, mattsinc approved these changes
Just approving on my end since I had requested changes previously -- @powerjg will also need to approve

2023-09-18 16:15 UTC, powerjg approved these changes

2023-09-18 16:53 UTC, merged

2023-09-18 16:54 UTC, mattsinc commented
Congrats @jebraun3 on your first commit (on gem5-resources)!  We'll have to keep an eye out with the companion commit on gem5 to make sure nothing breaks from this.