resources: Update ROI
gem5/gem5-resources pull request #54
Opened 2024-09-16 04:36 UTC by Harshil2107

- workbegin now is called after timer_start
- workend is called before timer_end

2024-09-17 17:34 UTC, studyztp requested changes
Thank you for making the changes! It looks good. I only have one suggestion to the LU's ROIs.

2024-09-17 17:34 UTC, studyztp commented on src/npb-24.04-imgs/npb-with-roi/NPB/NPB3.4-OMP/LU/ssor_hp.f90
>        call m5_work_begin_interface
I think both the `ssor` function in  `ssor_hp.f90` and `ssor_doac.f90` are called the same way as `ssor.f90`, which means there will be one warm up call followed by the actual call. In order to avoid calling the ROIs in the warm up call, we need to check the `niter` here just like in `ssor.f90`.
Here is a link to how `ssor_hp.f90` and `ssor_doac.f90` is compiled: https://github.com/gem5/gem5-resources/blob/stable/src/npb-24.04-imgs/npb-with-roi/NPB/NPB3.4-OMP/LU/Makefile#L24

2024-09-17 17:34 UTC, studyztp commented on src/npb-24.04-imgs/npb-with-roi/NPB/NPB3.4-OMP/LU/ssor_doac.f90
>        call m5_work_begin_interface
Same as the comment in `ssor_hp.f90`

2024-09-19 22:48 UTC, studyztp approved these changes

2024-10-04 19:12 UTC, powerjg commented
@studyztp can you re-review?

2024-10-04 19:12 UTC, powerjg approved these changes

2024-10-07 16:45 UTC, merged