resources: Add x86-gapbs on Ubuntu 22.04 disk image resource
gem5/gem5-resources pull request #6
Opened 2023-08-16 21:55 UTC by erin-le

This commit adds the files necessary to create an x86 Ubuntu 22.04 disk image containing the GAP Benchmark Suite. It only includes the files necessary to create the disk image, and not the disk image itself. The files in the directory "qemu_files" are used to create the disk image and launch a QEMU instance. The directory "packer_files" contains the files needed by Packer to install GAPBS onto the disk image. The README contains detailed instructions on how to build the disk image, and x86-gapbs-benchmarks-2204.py is a sample script.

After the disk image is built, it can be used as a DiskImageResource in a gem5 simulation.

2023-08-16 22:05 UTC, powerjg commented
@hnpl your review would be helpful!

@erin-le what testing have you done?

Finally, @KyleRoarty you mentioned that you figured out a way to build this without  separately launching qemu (I think). Could you let us know how you did that (and if you could provide a review that could be helpful as well).

2023-08-16 23:47 UTC, erin-le commented
I tested different combinations of sizes and benchmarks for the original disk image I made. After testing the original disk image, I wrote instructions to make the disk image, remade the disk image based on those, and ran a few simulations to check that the benchmarks would run and the simulation would finish properly. I did this again after editing the instructions and adding a few files.
I used synthetic graphs with sizes between 1 and 16, as well as the USA-road-d.NY.gr real graph. The benchmarks I tested were cc,bc,tc,pr,and bfs. For each benchmark, I tried the following sizes on the original disk:
bc: USA-road, 2, 4, 8, 10, 14
bfs: USA-road, 4, 8, 16
cc: USA-road, 2, 3, 10
pr: 2, 5, 6, 7, 8, 9, 12, 14, 16
tc: 2, 7, 10, 12, 16

2023-08-21 18:28 UTC, hnpl commented on src/x86-gapbs-ubuntu-22.04/packer_files/1.packages-install.sh
> +# Use `systemctl mask <service/target/socket/timer>` to stop a systemd object from starting during the booting time
The line 28-30 are comments for trimming systemd services. Since we are not removing systemd services, can you remove the comments?

2023-08-21 18:28 UTC, hnpl commented on src/x86-gapbs-ubuntu-22.04/qemu_files/cloud.txt
> +      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDg18gIYyZcGaAbhgZ1d20b0Id2AKIHxesNRFCoaJmrkAZfxbXJ6wpybtyLJizISQUoSoWugGThg25/Hkb8WP9CNvn4R/CJWnzB1TKblY5WmeTDDr0DDtl+2dtaZOTBccCXAWSyPVT3fmMmkxmTY/Ttz2D
This key should be generated by user. Reusing public keys could be a security issue.

2023-08-21 18:41 UTC, hnpl reviewed
There are a few comments to be addressed but this looks good to me.

2023-08-21 18:41 UTC, hnpl commented on src/x86-gapbs-ubuntu-22.04/qemu_files/get-disk-img.sh
> +qemu-img resize -f raw ./x86_64-hpc-2204.img +20G
This line adds about 20GiB of disk space to the disk, which is rather large if someone wants to download the disk image. User can always increase the disk size, so I think it's safe to minimize the disk size. I'm not sure what is the optimal size, but can you test with +3GiB or +5GiB?

2023-08-21 18:41 UTC, hnpl commented on src/x86-gapbs-ubuntu-22.04/qemu_files/flash0.img
I don't think we need to upload this file as the file can be generated by a script or by user.

2023-08-21 18:41 UTC, hnpl commented on src/x86-gapbs-ubuntu-22.04/qemu_files/flash1.img
I don't think we need to upload this file as the file can be generated by a script or by user.

2023-08-21 18:41 UTC, hnpl commented on src/x86-gapbs-ubuntu-22.04/packer_files/post-installation.sh
> +# mv /home/ubuntu/gem5/m5 /sbin
Can you remove the line 11-12 since they are commented out?

2023-08-21 18:41 UTC, hnpl commented on src/x86-gapbs-ubuntu-22.04/packer_files/2.m5-install.sh
> +git clone https://gem5.googlesource.com/public/gem5/
Can you change this link to https://github.com/gem5/gem5

2023-08-21 18:41 UTC, hnpl commented on src/x86-gapbs-ubuntu-22.04/x86-gapbs-benchmarks-2204.py
> +# class X86Board_sda(X86Board):
Can you add comments to the script explaining when and how to use line 179-189?

2023-08-21 18:41 UTC, hnpl commented on src/x86-gapbs-ubuntu-22.04/qemu_files/cloud.img
I don't think we need to upload this file as the file can be generated by a script or by user.

2023-08-21 18:41 UTC, hnpl commented on src/x86-gapbs-ubuntu-22.04/README.md
> +Please note that the `x86_64-hpc.json` included in packer_files/x86_64-hpc.json is a modified version of the one in the linked tutorial. All scripts except for the first two were removed, as they wer
```suggestion
Please note that the `x86_64-hpc.json` included in `packer_files/x86_64-hpc.json` is a modified version of the one in the linked tutorial. All scripts except for the first two were removed, as they weren't necessary for the GAPBS benchmarks, and `gapbs-install.sh` and `post-installation.sh` were added.
```

2023-08-22 21:51 UTC, BobbyRBruce requested changes
A few high-level comments here:

1. Perhaps I've missed it somewhere, but where do you add the ExitEvents? What have you addeded and where?
2. Should this be an update of the current x86-gapbs disk image (e.g., a Version 2 of it) or should this be a whole different resources? It seems to me like the former is correct.
3. Is the true intention here for this to be on the develop branch? If these changes are compatible with v23.0 then they should be on stable.

2023-08-22 21:51 UTC, BobbyRBruce commented on src/x86-gapbs-ubuntu-22.04/x86-gapbs-benchmarks-2204.py
> +# Copyright (c) 2021 The Regents of the University of California.
The copyright here is out-of-date.

2023-08-22 21:51 UTC, BobbyRBruce commented on src/x86-gapbs-ubuntu-22.04/x86-gapbs-benchmarks-2204.py
> +# Copyright (c) 2021 The Regents of the University of California.
Why are you adding an example script here. Shouldn't this be in "configs/examples/gem5_library/" in the main gem5 repo?

2023-08-23 15:15 UTC, kroarty-lanl reviewed
This is Kyle under my work account, Jason asked me to review this. 

As Jason mentioned, I've got a way to encapsulate this all into a packer script, but we determined it'd be better to get this checked in and I'll provide a pull request to update this to the format I use.

I have some feedback that could either be implemented here, or could wait until after when I submit my PR.

2023-08-23 15:15 UTC, kroarty-lanl commented on src/x86-gapbs-ubuntu-22.04/qemu_files/flash0.img
This isn't used in the qemu script, so it can be removed

2023-08-23 15:15 UTC, kroarty-lanl commented on src/x86-gapbs-ubuntu-22.04/qemu_files/flash1.img
ditto to flash0.img

2023-08-23 15:15 UTC, kroarty-lanl commented on src/x86-gapbs-ubuntu-22.04/qemu_files/qemu-launch.sh
> +     -drive if=none,id=cloud,file=cloud.img -device virtio-blk-pci,drive=cloud
It's possible to avoid compiling the cloud.txt into an img and passing it into qemu. [This](https://cloudinit.readthedocs.io/en/latest/reference/datasources/nocloud.html) is the doc page explaining it.

I've only used the http method, so I can't verify exactly how to make the file method work, but cloud.txt would need to be renamed to user-data, a meta-data file would need to be created (ie `touch meta-data`) and this line would be replaced with something like `-smbios type=1,serial=ds=nocloud;s=file://path/to/gem5-resources/src/x86-gapbs-ubuntu-22.04/qemu-files/`

Given that I'm not sure how the file path works (does it have to be absolute) there might not be value in this change as the users may still have to interact (execute shell script vs put their path in).

2023-08-23 15:15 UTC, kroarty-lanl commented on src/x86-gapbs-ubuntu-22.04/qemu_files/cloud.txt
> +      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDg18gIYyZcGaAbhgZ1d20b0Id2AKIHxesNRFCoaJmrkAZfxbXJ6wpybtyLJizISQUoSoWugGThg25/Hkb8WP9CNvn4R/CJWnzB1TKblY5WmeTDDr0DDtl+2dtaZOTBccCXAWSyPVT3fmMmkxmTY/Ttz2D
You can use a password instead of a ssh key by setting the top-level key `ssh_pwauth: true`

If you decide to do this, you can then replace `ssh-authorized-keys` with `plain_text_passwd: <password>`

Also if this change is made, make sure to verify that the packer install files still work. I know the `sudo: ['ALL=(ALL) NOPASSWD:ALL']` line is supposed to allow sudo without using a password, but I ran into some issues (which may just be me messing up) and ended up piping the password into sudo.

2023-08-23 15:15 UTC, kroarty-lanl commented on src/x86-gapbs-ubuntu-22.04/packer_files/x86_64-hpc.json
> +            "ssh_agent_auth": true,
If using ssh_pwauth, remove lines 11-14, add an ssh_password variable to variables, and add in a line here 
```
"ssh_password": "{{ user `ssh_password` }}"
```

2023-08-23 15:15 UTC, kroarty-lanl commented on src/x86-gapbs-ubuntu-22.04/qemu_files/qemu-launch.sh
> +     -drive if=none,id=cloud,file=cloud.img -device virtio-blk-pci,drive=cloud
Additional comment: Is this going to use kvm by default? If not, would it be worth adding to the qemu command?

2023-08-24 19:28 UTC, erin-le commented
> 1. Perhaps I've missed it somewhere, but where do you add the ExitEvents? What have you addeded and where?
>2. Should this be an update of the current x86-gapbs disk image (e.g., a Version 2 of it) or should this be a whole different resources? It seems to me like the former is correct.
>3. Is the true intention here for this to be on the develop branch? If these changes are compatible with v23.0 then they should be on stable.

Responses to Bobby's review:
1. I'm not entirely sure. I think there's an ExitEvent added in `packer_files/gem5-init.sh` (a script that is run on the disk image), where the simulation exits after the benchmark finishes on the disk image, but I could also be misunderstanding what an ExitEvent is.
2. It looks like the intention was for this to be an update of the current x86-gapbs disk image. In this case, should I put the added `x86-gapbs-ubuntu-22.04` directory under the existing `x86-ubuntu` directory and group the files currently in the `x86-ubuntu` directory into a sub-directory?
3. I mainly made the pull request on the develop branch because of the instructions in the README. Would you want me to switch it to the stable branch?

2023-08-24 19:32 UTC, erin-le commented on src/x86-gapbs-ubuntu-22.04/x86-gapbs-benchmarks-2204.py
> +# Copyright (c) 2021 The Regents of the University of California.
I wasn't really sure where to put it. In that case, should I remove the file and make a new PR for it in the gem5 repo?

2023-09-10 18:29 UTC, abmerop commented
Is this something that could be / is intended to be a generic X86 disk image?  I would like to update the GPU disk image to 22.04, but what I want to do is start with a generic X86 disk and install the additional packages to a secondary disk rather than having multiple GBs of redundant files.

2024-09-05 00:57 UTC, closed without merging