resources: add scripts to make and extract arm kernel
gem5/gem5-resources pull request #60
Opened 2024-10-29 22:19 UTC by Harshil2107

2024-10-29 22:23 UTC, Harshil2107 commented
I am adding gem5-bridge driver based on #48

2024-10-30 00:25 UTC, powerjg commented on src/ubuntu-generic-diskimages/scripts/post-installation.sh
> +apt-get install -y fakeroot build-essential crash kexec-tools makedumpfile kernel-wedge
I doubt you need these packages

2024-10-30 00:25 UTC, powerjg commented on src/ubuntu-generic-diskimages/scripts/post-installation.sh
> +cp /boot/config-$(uname -r) .config
It looks like you are not applying the ubuntu patches to the kernel. You should add something like `patch < linux_6.8.0-47.47`. You'll have to figure out the right directory and the exact command. You may also have to unzip the diff.

2024-10-30 00:25 UTC, powerjg commented on src/ubuntu-generic-diskimages/scripts/post-installation.sh
> +git clone https://github.com/nkrim/gem5.git --depth=1 --filter=blob:none --no-checkout --sparse --single-branch --branch=gem5-bridge
I assume this is just a placeholder, but don't forget to fix this.

2024-10-30 19:54 UTC, Harshil2107 commented on src/ubuntu-generic-diskimages/scripts/post-installation.sh
> +cp /boot/config-$(uname -r) .config
I tried to apply the patch but it looks like it is aldready applied. I also looked at the make file of the diff and the source and it looks like the changes from the diff are already in the source.

2024-11-18 18:50 UTC, erin-le submitted a review, later dismissed
I tested this by building the disk image, then using the disk image and kernel as resources in a script that Harshil provided. It boots, so this LGTM

2024-11-22 23:44 UTC, powerjg commented on src/ubuntu-generic-diskimages/http/arm-24-04/user-data
> +      size: 50726691840
Is this size necessary?

2024-11-22 23:49 UTC, Harshil2107 commented on src/ubuntu-generic-diskimages/http/arm-24-04/user-data
> +      size: 50726691840
with the docker method we can go back to the original size of 5 gb, I will change this.

2024-11-22 23:51 UTC, Harshil2107 commented
I think going for the method that I used in the 22.04 image, is better than the one that is used in 24.04 image. The only issue is that you have to give write permissions to the the directory we are mounting to the docker to get the kernel and the modules.

does this look good, If so I can update the 24.04 image as well

2024-11-22 23:51 UTC, powerjg commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +apt source linux-image-unsigned-6.8.0-47-generic
If this is run on the host, then you've made this quite host-dependent. E.g., it probably won't work on x86.

2024-11-22 23:51 UTC, powerjg commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +chmod a+x debian/scripts/misc/*
This should not be required. If it is, you're doing something wrong.

2024-11-22 23:51 UTC, powerjg commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +git clone https://github.com/nkrim/gem5.git --depth=1 --filter=blob:none --no-checkout --sparse --single-branch --branch=gem5-bridge
get this committed to gem5 and use the gem5 source.

2024-11-22 23:51 UTC, powerjg commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> + chmod 777 my-arm-5.15.167-kernel
This should not be needed.

2024-11-22 23:51 UTC, powerjg commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +docker run --rm -it -u $UID:$GID -v ./linux-6.8.0:/workspace/source -v ./output:/workspace/output --name kernel-builder ubuntu-kernel-build
You should not run a docker container interactively. Write a script and execute the script in the docker container.

2024-11-22 23:51 UTC, powerjg commented on src/ubuntu-generic-diskimages/22.04-dockerfile/Dockerfile
> +WORKDIR /workspace
Why not install the sources here?

In fact why don't you just use a dockerfile to do everything?

2024-11-25 22:33 UTC, Harshil2107 commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +apt source linux-image-unsigned-6.8.0-47-generic
I have moved the building process to the dockerfile instead of host.

2024-11-25 22:34 UTC, Harshil2107 commented on src/ubuntu-generic-diskimages/22.04-dockerfile/Dockerfile
> +WORKDIR /workspace
I updated the dockerfiles so that kernel is built in the dockerfiles

2024-11-26 19:15 UTC, Harshil2107 commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +chmod a+x debian/scripts/misc/*
I removed these statements and the kernel compilation works.

2024-11-26 19:33 UTC, Harshil2107 commented
I built and tests the gem5 bridge driver with both the 22.04 and 24.04 disk images. I built the base image and then built the npb image using this base image. I was able to run the benchmark without sudo in gem5.

The only blocker to his now should be getting the m5 driver code in gem5.

2024-12-04 01:02 UTC, erin-le reviewed
Looks good overall. There are just a few typos and minor things that could be added in `make-kernel-and-gem5-bridge-driver.md`.

2024-12-04 01:02 UTC, erin-le commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +  cd src/ubuntu-generic-diskiamges/22.04-dockerfile
```suggestion
  cd src/ubuntu-generic-diskimages/22.04-dockerfile
```

2024-12-04 01:02 UTC, erin-le commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +    source      = "my-arm-5.15.167-kernel"
```suggestion
    source      = "my-arm-5.15.167-kernel/5.15.167"
```

2024-12-04 01:02 UTC, erin-le commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +  cd src/ubuntu-generic-diskiamges/24.04-dockerfile
```suggestion
  cd src/ubuntu-generic-diskimages/24.04-dockerfile
```

2024-12-04 01:02 UTC, erin-le commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +- Add a Packer file provisioner to copy the modules to the disk image:
Might be good to specify that they should paste this below the other file provisioners, in case it matters that it's not below the shell provisioner, and that the path is `ubuntu-generic-diskimages/packer-scripts/arm-ubuntu.pkr.hcl`.

2024-12-04 01:02 UTC, erin-le commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +- Update the post-install script to move the modules into the correct location and regenerate the initramfs:
Might be good to specify the path to the script as `ubuntu-generic-diskimages/scripts/post-installation.sh` and also mention a specific place in the script that the snippet could go, such as above `echo "Post Installation Done"
`.

2024-12-04 01:02 UTC, erin-le commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +- Add a Packer file provisioner to copy the modules to the disk image:
Same comments as above; path and location in script

2024-12-04 01:02 UTC, erin-le commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +- Update the post-install script to move the modules into the correct location and regenerate the initramfs:
Same comments as above; path and location in script.

2024-12-04 01:02 UTC, erin-le commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +- Use the disk image and the kernel to run a gem5 filesystem simulation, ensuring the new kernel and modules are correctly set up.
You may also want to consider including an example, such as the following:
```
image = DiskImageResource("/path/to/gem5-resources/src/ubuntu-generic-diskimages/arm-disk-image-22-04/arm-ubuntu")
image._root_partition = "2"

board.set_kernel_disk_workload(
    kernel=KernelResource("/path/to/gem5-resources/src/ubuntu-generic-diskimages/my-arm-5.15.167-kernel/vmlinux"),
    disk_image=image,
    bootloader=obtain_resource("arm64-bootloader-foundation"),
)

```

2024-12-04 19:29 UTC, powerjg requested changes

2024-12-04 19:29 UTC, powerjg commented on src/ubuntu-generic-diskimages/24.04-dockerfile/Dockerfile
> +CMD ["/bin/bash"]
Should be removed so the image won't be used interactively.

2024-12-04 19:29 UTC, powerjg commented on src/ubuntu-generic-diskimages/24.04-dockerfile/Dockerfile
> +RUN git clone https://github.com/nkrim/gem5.git --depth=1 --filter=blob:none --no-checkout --sparse --single-branch --branch=gem5-bridge && \
Must be changed before merging

2024-12-04 22:32 UTC, erin-le commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +- Add a Packer file provisioner to copy the modules to the disk image.
```suggestion
- Add a Packer file provisioner to copy the modules to the disk image. The Packer script is located at `ubuntu-generic-diskimages/packer-scripts/arm-ubuntu.pkr.hcl`.
```

2024-12-04 22:32 UTC, erin-le commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +Make sure that this provisioner is added before the shell provisioner as we will used these files in the `post-installation.sh`:
```suggestion
Make sure that this provisioner is added before the shell provisioner, as these files are used when the shell provisioner runs`post-installation.sh`:
```

2024-12-04 22:32 UTC, erin-le commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +- Add a Packer file provisioner to copy the modules to the disk image.
```suggestion
- Add a Packer file provisioner to copy the modules to the disk image. The Packer script is located at `ubuntu-generic-diskimages/packer-scripts/arm-ubuntu.pkr.hcl`.
```

2024-12-04 22:32 UTC, erin-le commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +- You can use the following code snipped to use the disk image and kernel you made.
```suggestion
- You can use the following code snippet to use the disk image and kernel you made.
```

2024-12-04 22:32 UTC, erin-le commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +- Update the post-install script to move the modules into the correct location and regenerate the initramfs.
```suggestion
- Add the following code snippet to the post-install script to move the modules into the correct location and regenerate the initramfs. The post-install script is located at `ubuntu-generic-diskimages/scripts/post-installation.sh`.
```

2024-12-04 22:32 UTC, erin-le commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +Make sure the modules are moved before using `gem5-bridge` or compiling benchmarks with `gem5-bridge`:
```suggestion
Make sure the modules are moved before using `gem5-bridge` or compiling benchmarks with `gem5-bridge`, i.e. add the snippet before the line `echo "Building and installing gem5-bridge (m5) and libm5"`:
```

2024-12-04 22:32 UTC, erin-le commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +- Update the post-install script to move the modules into the correct location and regenerate the initramfs.
```suggestion
- Add the following code snippet to the post-install script to move the modules into the correct location and regenerate the initramfs. The post-install script is located at `ubuntu-generic-diskimages/scripts/post-installation.sh`.
```

2024-12-04 22:32 UTC, erin-le commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
> +Make sure the modules are moved before using `gem5-bridge` or compiling benchmarks with `gem5-bridge`:
```suggestion
Make sure the modules are moved before using `gem5-bridge` or compiling benchmarks with `gem5-bridge`, i.e. add the snippet before the line `echo "Building and installing gem5-bridge (m5) and libm5"`:
```

2024-12-04 22:32 UTC, erin-le commented on src/ubuntu-generic-diskimages/make-kernel-and-gem5-bridge-driver.md
>  - Use the disk image and the kernel to run a gem5 filesystem simulation, ensuring the new kernel and modules are correctly set up.
```suggestion
- Use the disk image and the kernel to run a gem5 filesystem simulation, ensuring the new kernel and modules are correctly set up. See the bottom of this file for an example.
```

2025-01-09 21:10 UTC, mahyarsamani commented
@Harshil2107 Please update the documentation on how to increase the size of the disk-image. I would like to see an example of how each size is calculated--- rather than saying size A has to be at least 1 megabyte more than size B. In my experience when I tried to resize the image for ~20GB, this is what I had to do. 

UEFI_size: First partition size defined in http/user-data; I am assume it is the size of the partition allocated for UEFI. This in your case is the magical number 564133888.
root_size: Second partition size defined in http/user-data; This is the size of the root partition (/) in the disk-image, this is what the user defines. In my case, I am using 20909654016.
mystical_size: Size of the unexplained mysterious 1 MB we have to account for. This is 1048576.

Using this information, the disk_size is equal to 564133888 + 20909654016 + 1048576 = 21474836480 (which btw is exactly 20GiB (GibiBytes). Please note that the unit for disk_size in .hcl is not MibiBytes (2^20), it is rather MegaBytes (10^6). Which means you have to divide the final number by 1_000_000 which will give you 21474.833. In my case, I just rounded that to 21600.

2025-01-09 21:10 UTC, mahyarsamani commented
> @Harshil2107 Please update the documentation on how to increase the size of the disk-image. I would like to see an example of how each size is calculated--- rather than saying size A has to be at least 1 megabyte more than size B. In my experience when I tried to resize the image for ~20GB, this is what I had to do.
> 
> UEFI_size: First partition size defined in http/user-data; I am assume it is the size of the partition allocated for UEFI. This in your case is the magical number 564133888. root_size: Second partition size defined in http/user-data; This is the size of the root partition (/) in the disk-image, this is what the user defines. In my case, I am using 20909654016. mystical_size: Size of the unexplained mysterious 1 MB we have to account for. This is 1048576.
> 
> Using this information, the disk_size is equal to 564133888 + 20909654016 + 1048576 = 21474836480 (which btw is exactly 20GiB (GibiBytes). Please note that the unit for disk_size in .hcl is not MibiBytes (2^20), it is rather MegaBytes (10^6). Which means you have to divide the final number by 1_000_000 which will give you 21474.833. In my case, I just rounded that to 21600.

This worked btw!

2025-01-09 21:54 UTC, Harshil2107 commented
@mahyarsamani I updated the documentation with example #65

2025-01-09 22:05 UTC, mahyarsamani commented
I think the iso link for 24.04 is outdated.

2025-01-22 22:44 UTC, mahyarsamani commented
I want to propose holding off on getting this merged. I faced a few challenges when I tried to use the scripts here to get my packages installed and get them to work without effecting other parts of the system setup (e.g. serial-getty@.service, gem5_init.sh, ...). I have created a draft pr for it here: https://github.com/gem5/gem5-resources/pull/68

2025-07-31 21:58 UTC, closed without merging